### ISSUE TITLE
Ignore unmute on world switch

### ISSUE THREAD

**Issue by burritosoftware** [tetra-fox/UnmuteSound#2]
When muted, and I join a new world and have my "join muted" setting off in VRC native settings, I hear the unmuted sound. I'd prefer this to be not heard when joining a new world.

**Comment by tetra-fox** [comment]
This is technically intended behavior as VRChat calls the mute toggle method, which this mod patches, when leaving a world if you have that setting on. However, I do understand the annoyance and will look into a workaround for this.

**Comment by tetra-fox** [comment]
Fixed in 5810bc4. Just submitted the update to VRCMG. However, I'm still waiting on 1.0.1 to be approved, so I'm not sure how long it will take for 1.0.2 to be approved. In the meantime, you can download 1.0.2 [here](https://github.com/tetra-fox/UnmuteSound/releases/tag/1.0.2).
